-- Generated by matugen. Do not edit.
local c = {
  bg       = "#17111a",
  fg       = "#ebdfec",
  surface  = "#17111a",
  primary  = "#e2b5ff",
  secondary= "#e2b5ff",
  error    = "#ffb4ab",
}

vim.cmd("highlight clear")
vim.o.termguicolors = true
vim.g.colors_name = "matugen"

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

hi("Normal",       { fg = c.fg, bg = c.bg })
hi("NormalNC",     { fg = c.fg, bg = c.bg })
hi("CursorLine",   { bg = c.surface })
hi("Visual",       { bg = c. primary, fg = c.bg})
hi("LineNr",       { fg = c.secondary })
hi("CursorLineNr", { fg = c.primary, bold = true })
hi("StatusLine",   { fg = c.fg, bg = c.surface })
hi("ErrorMsg",     { fg = c.error })
