-- Generated by matugen. Do not edit.
local c = {
  bg       = "#{{colors.background.default.hex_stripped}}",
  fg       = "#{{colors.on_background.default.hex_stripped}}",
  surface  = "#{{colors.surface.default.hex_stripped}}",
  primary  = "#{{colors.primary.default.hex_stripped}}",
  secondary= "#{{colors.secondary.default.hex_stripped}}",
  error    = "#{{colors.error.default.hex_stripped}}",
}

vim.cmd("highlight clear")
vim.o.termguicolors = true
vim.g.colors_name = "matugen"

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

hi("Normal",       { fg = c.fg, bg = c.bg })
hi("NormalNC",     { fg = c.fg, bg = c.bg })
hi("CursorLine",   { bg = c.surface })
hi("Visual",       { bg = c.surface })
hi("LineNr",       { fg = c.surface })
hi("CursorLineNr", { fg = c.primary })
hi("StatusLine",   { fg = c.fg, bg = c.surface })
hi("ErrorMsg",     { fg = c.error })
